### ISSUE TITLE
first run `shipjs prepare` in ci fails with don't understandable error

### ISSUE THREAD

**Issue by jeetiss** [algolia/shipjs#561]
**Describe the bug**
First run `shipjs prepare --yes` fails with strange error!
https://github.com/globis-org/frontend-standard/commit/75174cf562831a93f205e35eb0fcc56baa986adf/checks?check_suite_id=373443031#step:6:40

I think will be better if we write something like: "you need run `shipjs prepare` manually first time"

**To Reproduce**
1. install shipjs with github actions
2. run manual prepare from actions
3. shipjs fails

**Expected behavior**
shipjs fails with clear message

**Comment by eunjae-lee** [comment]
Oh okay. The prompt pops up because of the missing tag.

I think

1. When --yes is given and git tag is missing l, we should throw an error instead of asking to choose commits. Because when attaching --yes, people expect no prompt.

2. We add an option to `prepare` command. 

```
shipjs prepare --commit-from 75174c
```

3. When --yes is given and tag is missing, we throw an error and tell user to add --commit-from option. We should show example commands for both normal command line and github actions.

4. And we should modify our github actions so that user can do something like

```
@shipjs preprare --commit-from 75174c
```

What do you think?

**Comment by jeetiss** [comment]
1-3 points sound legit for me, but I not sure about 4! How can we provide option to github actions through issues comment? Is it possible?)

**Comment by eunjae-lee** [comment]
> 1-3 points sound legit for me, but I not sure about 4! How can we provide option to github actions through issues comment? Is it possible?)

We might be able to comment a list of recent 10-20 commits and let user choose?
But even if so, user has to leave another comment including the commit hash.
Then it just sounds like `@shipjs preprare --commit-from 75174c`.

Any idea?

**Comment by eunjae-lee** [comment]
1. 
2. #561
3. 
4. ?

**Comment by eunjae-lee** [comment]
Not sure about 4, and I don't even know how to do it.
Last time I tried it but couldn't find any way to manipulate content of github issue comments.
